{{ badge }}

In [2]:
import torch
from scipy.misc import face

In [40]:
img = face().astype('float')
img = torch.tensor(img)
batch = img.permute(2, 0, 1)
batch = batch.unsqueeze(0)
# batch.shape
loader = [(batch, '')]

In [48]:
nimages = 0
mean = 0.
std = 0.

for batch, _ in loader:

    print(batch.shape)
    
    batch = batch.view(data.size(0), batch.size(1), -1)

    print(batch.shape)
    
    # update total number of images
    nimages += batch.size(0)
    # compute mean and std here
    mean += batch.mean(2).sum(0)
    std += batch.std(2).sum(0)
    
    print(nimages)
    print(mean)
    print(std)
    
mean /= nimages
std /= nimages

print(mean)
print(std)

torch.Size([1, 3, 768, 1024])
torch.Size([1, 3, 786432])
1
tensor([110.6760, 117.7298, 102.0824], dtype=torch.float64)
tensor([55.1072, 56.4377, 59.8056], dtype=torch.float64)
tensor([110.6760, 117.7298, 102.0824], dtype=torch.float64)
tensor([55.1072, 56.4377, 59.8056], dtype=torch.float64)


In [60]:
import torch
from torch.utils.data import TensorDataset, DataLoader

data = torch.randn(64, 3, 28, 28)
labels = torch.zeros(64, 1)
dataset = TensorDataset(data, labels)
loader = DataLoader(dataset, batch_size=8)

nimages = 0
mean = 0.
std = 0.
for batch, _ in loader:
    # Rearrange batch to be the shape of [B, C, W * H]
    batch = batch.view(batch.size(0), batch.size(1), -1)
    # Update total number of images
    nimages += batch.size(0)
    # Compute mean and std here
    mean += batch.mean(2).sum(0) 
    std += batch.std(2).sum(0)

# Final step
mean /= nimages
std /= nimages

print(mean)
print(std)

tensor([ 0.0091, -0.0010,  0.0024])
tensor([1.0035, 0.9965, 0.9973])
